### PR TITLE
Apply all config in .editorconfig to jscs

### PR DESCRIPTION
**Pull request by Johann-S**
I move the config of jscs to a separate file and added all config in the .editorconfig into the jscs config

### CODE REVIEW

**Comment by Frozenfire92** [comment]
Hey @Johann-S 

Thanks for the contribution. Can you fix up two quick things

1) your .jscsrc file has spaces as well as tab characters, change this to spaces only
2) Move the .jscsrc to the root directory with the other dotfiles

After that I will be glad to merge it in :)

**Comment by Johann-S** [comment]
Yes sure I'll fix that things. Thank you for your feedbacks.

**Comment by Johann-S** [comment]
If you prefer I can squash my two commits

**Comment by Frozenfire92** [comment]
Thanks @Johann-S 

No need to squash it will be ok :) I will merge this in after work today

**Pull request merged**
